/**
 * @fileoverview gRPC-Web generated client stub for openbytes
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: capture.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.openbytes = require('./capture_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.openbytes.CapturesClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.openbytes.CapturesPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.openbytes.Capture,
 *   !proto.openbytes.Packet>}
 */
const methodDescriptor_Captures_List = new grpc.web.MethodDescriptor(
  '/openbytes.Captures/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.openbytes.Capture,
  proto.openbytes.Packet,
  /**
   * @param {!proto.openbytes.Capture} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.openbytes.Packet.deserializeBinary
);


/**
 * @param {!proto.openbytes.Capture} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.openbytes.Packet>}
 *     The XHR Node Readable Stream
 */
proto.openbytes.CapturesClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/openbytes.Captures/List',
      request,
      metadata || {},
      methodDescriptor_Captures_List);
};


/**
 * @param {!proto.openbytes.Capture} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.openbytes.Packet>}
 *     The XHR Node Readable Stream
 */
proto.openbytes.CapturesPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/openbytes.Captures/List',
      request,
      metadata || {},
      methodDescriptor_Captures_List);
};


module.exports = proto.openbytes;

