/**
 * @fileoverview gRPC-Web generated client stub for openbytes
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: capture.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js')
const proto = {};
proto.openbytes = require('./capture_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.openbytes.CapturesClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.openbytes.CapturesPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.google.protobuf.ListValue>}
 */
const methodDescriptor_Captures_Device = new grpc.web.MethodDescriptor(
  '/openbytes.Captures/Device',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  google_protobuf_struct_pb.ListValue,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_struct_pb.ListValue.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.ListValue)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.ListValue>|undefined}
 *     The XHR Node Readable Stream
 */
proto.openbytes.CapturesClient.prototype.device =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/openbytes.Captures/Device',
      request,
      metadata || {},
      methodDescriptor_Captures_Device,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.ListValue>}
 *     Promise that resolves to the response
 */
proto.openbytes.CapturesPromiseClient.prototype.device =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/openbytes.Captures/Device',
      request,
      metadata || {},
      methodDescriptor_Captures_Device);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.openbytes.Capture,
 *   !proto.openbytes.Packet>}
 */
const methodDescriptor_Captures_List = new grpc.web.MethodDescriptor(
  '/openbytes.Captures/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.openbytes.Capture,
  proto.openbytes.Packet,
  /**
   * @param {!proto.openbytes.Capture} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.openbytes.Packet.deserializeBinary
);


/**
 * @param {!proto.openbytes.Capture} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.openbytes.Packet>}
 *     The XHR Node Readable Stream
 */
proto.openbytes.CapturesClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/openbytes.Captures/List',
      request,
      metadata || {},
      methodDescriptor_Captures_List);
};


/**
 * @param {!proto.openbytes.Capture} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.openbytes.Packet>}
 *     The XHR Node Readable Stream
 */
proto.openbytes.CapturesPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/openbytes.Captures/List',
      request,
      metadata || {},
      methodDescriptor_Captures_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.openbytes.Capture,
 *   !proto.openbytes.Point>}
 */
const methodDescriptor_Captures_Traffic = new grpc.web.MethodDescriptor(
  '/openbytes.Captures/Traffic',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.openbytes.Capture,
  proto.openbytes.Point,
  /**
   * @param {!proto.openbytes.Capture} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.openbytes.Point.deserializeBinary
);


/**
 * @param {!proto.openbytes.Capture} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.openbytes.Point>}
 *     The XHR Node Readable Stream
 */
proto.openbytes.CapturesClient.prototype.traffic =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/openbytes.Captures/Traffic',
      request,
      metadata || {},
      methodDescriptor_Captures_Traffic);
};


/**
 * @param {!proto.openbytes.Capture} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.openbytes.Point>}
 *     The XHR Node Readable Stream
 */
proto.openbytes.CapturesPromiseClient.prototype.traffic =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/openbytes.Captures/Traffic',
      request,
      metadata || {},
      methodDescriptor_Captures_Traffic);
};


module.exports = proto.openbytes;

